LangString addOrReinstall ${LANG_FRENCH} "Réparer NetsuRush (recommandé)"
LangString alreadyInstalled ${LANG_FRENCH} "NetsuRush est déjà installé"
LangString alreadyInstalledLong ${LANG_FRENCH} "Cette version de NetsuRush est déjà présente. Réparer remplace les fichiers de l'application sans supprimer vos projets, modèles ni réglages."
LangString appRunning ${LANG_FRENCH} "NetsuRush est en cours d'exécution. Fermez l'application puis réessayez."
LangString appRunningOkKill ${LANG_FRENCH} "NetsuRush est en cours d'exécution.$\nCliquez sur OK pour la fermer."
LangString chooseMaintenanceOption ${LANG_FRENCH} "Choisissez l'action à effectuer."
LangString choowHowToInstall ${LANG_FRENCH} "Une version de NetsuRush est déjà installée. Choisissez l'action à effectuer."
LangString createDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau"
LangString dontUninstall ${LANG_FRENCH} "Mettre à jour sans désinstaller (recommandé)"
LangString dontUninstallDowngrade ${LANG_FRENCH} "Conserver la version actuelle (le retour en arrière sans désinstallation est désactivé)"
LangString failedToKillApp ${LANG_FRENCH} "NetsuRush n'a pas pu être fermé. Fermez-le manuellement puis réessayez."
LangString installingWebview2 ${LANG_FRENCH} "Installation de WebView2…"
LangString newerVersionInstalled ${LANG_FRENCH} "Une version plus récente de NetsuRush est déjà installée. Sélectionnez l'action souhaitée puis cliquez sur Suivant."
LangString older ${LANG_FRENCH} "ancienne"
LangString olderOrUnknownVersionInstalled ${LANG_FRENCH} "NetsuRush $R4 est déjà installé. La mise à jour conserve vos données ; la réparation remplace seulement les fichiers de l'application."
LangString silentDowngrades ${LANG_FRENCH} "Le retour vers une version antérieure est désactivé pour l'installation silencieuse.$\n"
LangString unableToUninstall ${LANG_FRENCH} "Impossible de désinstaller NetsuRush."
LangString uninstallApp ${LANG_FRENCH} "Désinstaller NetsuRush"
LangString uninstallBeforeInstalling ${LANG_FRENCH} "Désinstaller puis installer"
LangString unknown ${LANG_FRENCH} "inconnue"
LangString webview2AbortError ${LANG_FRENCH} "L'installation de WebView2 a échoué. NetsuRush nécessite WebView2 pour fonctionner."
LangString webview2DownloadError ${LANG_FRENCH} "Erreur lors du téléchargement de WebView2 : $0"
LangString webview2DownloadSuccess ${LANG_FRENCH} "WebView2 a été téléchargé."
LangString webview2Downloading ${LANG_FRENCH} "Téléchargement de WebView2…"
LangString webview2InstallError ${LANG_FRENCH} "L'installation de WebView2 a échoué (code $1)."
LangString webview2InstallSuccess ${LANG_FRENCH} "WebView2 est installé."
LangString deleteAppData ${LANG_FRENCH} "Supprimer les données de l'application"
