"""Traductions courtes des erreurs utilisateur renvoyées par les sidecars JSON."""
import os


_MESSAGES = {
    "fr": {
        "unknown_command": "commande inconnue{detail}",
        "required_name": "Nom requis.", "required_id": "id requis.",
        "required_char_id": "char_id requis.",
        "required_source_target": "source_id et target_id requis.",
        "same_character": "Un personnage ne peut pas fusionner avec lui-même.",
        "character_not_found": "Personnage introuvable.",
        "no_face_to_save": "Aucun visage détecté à enregistrer.",
        "character_no_samples": "Ce personnage n'a aucun échantillon de visage.",
        "no_characters": "Aucun personnage enregistré.",
        "empty_query": "requête vide",
        "no_confident_shot": "Aucun plan assez sûr pour {who} : les visages reconnus sont sous le seuil de confiance. Ajoute des échantillons plus variés (Hub Visages) puis relance la reconnaissance.",
        "no_recognized_shot": "Aucun plan reconnu pour {who} — ajoute-lui des échantillons de visage (Hub Visages) puis lance « Indexer les visages » et la reconnaissance.",
        "no_shared_shot": "Aucun plan ne réunit tous les personnages cités.",
        "partial_character_overlap": "Aucun plan ne réunit les {total} personnages cités : voici ceux qui en réunissent {found}.",
        "cited_character": "un personnage cité",
        "face_engine_missing": "Aucun moteur visage disponible (poids/dépendances manquants — relance l'installation).",
        "image_unreadable_error": "Image illisible : {error}",
        "no_indexed_face": "Aucun visage indexé. Lance d'abord « Indexer les visages ».",
        "no_reference_face": "Aucun visage détecté dans les références.",
        "siglip_missing": "Dépendances SigLIP 2 absentes : pip install -r requirements.txt ({error})",
        "video_dimensions": "dimensions vidéo introuvables{detail}",
        "gif_dimensions": "dimensions GIF introuvables : {path}",
        "frame_missing": "frame introuvable à {time:.3f}s",
        "write_source_png": "écriture PNG source échouée",
        "write_upscaled_png": "écriture PNG upscalée échouée",
        "write_depth_png": "écriture PNG profondeur échouée",
        "write_alpha_png": "écriture PNG alpha échouée",
        "write_preview_png": "écriture PNG aperçu échouée",
        "write_interpolated_png": "écriture PNG interpolée échouée",
        "unknown_preview_mode": "mode d'aperçu inconnu : {mode}",
        "depth_unavailable": "depth indisponible{detail}",
        "removebg_unavailable": "removeBG indisponible{detail}",
        "interpolation_unavailable": "interpolation indisponible{detail}",
        "load_depth_failed": "chargement depth échoué{detail}",
        "load_removebg_failed": "chargement rembg échoué{detail}",
        "load_rife_failed": "chargement RIFE échoué{detail}",
        "encoder_stopped": "ffmpeg encodeur interrompu (codec indisponible ?)",
        "empty_output": "fichier de sortie vide", "empty_gif": "GIF de sortie vide",
        "empty_alpha": "séquence alpha vide", "empty_depth": "séquence de profondeur vide",
        "ffmpeg_code": "ffmpeg encode code {code}",
        "image_unreadable_path": "image illisible : {path}",
        "write_upscaled_image": "écriture image upscalée échouée",
        "unexpected_rembg": "sortie rembg inattendue (forme {shape})",
        "spandrel_not_i2i": "modèle Spandrel non image-to-image : {path}","gmfss_missing": "GMFSS incomplet : {path} — réinstallez le modèle depuis Paramètres › Modèles","drba_arch_missing": "architecture DRBA absente pour {model} — installez le modèle depuis Paramètres › Modèles","drba_weights_missing": "poids DRBA absents : {file}","rife_arch_missing": "architecture RIFE absente pour {model} — installez le modèle depuis Paramètres › Modèles","rife_weights_missing": "poids RIFE absents : {file}","ntire_code_missing": "code NTIRE absent pour {model} — installez le modèle depuis Paramètres › Modèles ({error})",
        "weight_missing": "poids absent : {file}. Télécharge le modèle depuis {url} puis mets-le dans {folder}",
        "model_download_failed": "téléchargement modèle échoué ({file}) : {error}",
        "video_not_found": "vidéo introuvable : {path}",
        "no_video": "aucune vidéo ouverte", "point_not_found": "point introuvable",
        "nothing_to_undo": "aucun point à annuler", "no_restore": "aucune sauvegarde à restaurer",
        "track_before_dedupe": "lance le suivi avant de dédoublonner",
        "add_point_first": "pose au moins un point d'abord",
        "no_matte_scope": "aucune matte pour la portée « {scope} »",
        "track_before_export": "lance le suivi avant d'exporter",
        "no_mask_frame": "aucun masque sur cette image — pose des points ou lance le suivi",
        "engine_missing": "{engine} absent — installe-le dans Paramètres › Modèles ({error})",
        "engine_failed": "{engine} a échoué : {error}",
        "fine_matte_unreadable": "aperçu du matte fin illisible",
        "track_before_refine": "lance le suivi avant d'affiner le matte",
        "no_propagated_matte": "aucune matte propagée — lance le suivi d'abord",
        "segment_before_remove": "segmente et propage l'objet avant de le supprimer",
        "remove_engine_unwired": "moteur de suppression « {engine} » pas encore câblé — utilise {fallback}",
        "engine_weights_missing": "poids {engine} absents — télécharge-les dans Paramètres › Modèles",
        "engine_unavailable": "moteur {engine} indisponible : {error}",
        "sam_package_missing": "package sam2 indisponible (pip install sam2) : {error}",
        "sam_weights_missing": "poids SAM introuvables — installe SAM 2.1 dans Paramètres › Modèles","sam3_package_missing":"package sam3 indisponible (installe SAM 3.1 dans Paramètres › Modèles) : {error}","sam3_cuda_required":"SAM 3.1 exige un GPU NVIDIA (CUDA) : le modèle amont n'a pas de mode processeur. Utilise SAM 2.1 sur cette machine.","sam3_weights_missing":"poids SAM 3.1 introuvables — installe-les dans Paramètres › Modèles",
        "no_frame_to_process": "aucune frame à traiter", "empty_frame_range": "sous-plage de frames vide",
        "preview_out_of_range": "frame d'aperçu hors de la sous-plage",
        "whisper_missing": "faster-whisper absent : pip install faster-whisper ({error})",
        "parakeet_missing": "Parakeet absent : pip install onnx-asr[gpu,hub] ({error})",
        "silero_missing": "Silero VAD absent : pip install silero-vad ({error})",
        "librosa_missing": "librosa absent : pip install librosa ({error})",
        "ben2_missing": "package ben2 absent (installe BEN2 dans Paramètres › Modèles) : {error}","da3_missing":"package depth_anything_3 absent (installe Depth Anything 3 dans Paramètres › Modèles) : {error}","unknown_seg_model":"modèle de détourage inconnu : {model}",
    },
    "en": {
        "unknown_command":"unknown command{detail}","required_name":"Name is required.","required_id":"id is required.","required_char_id":"char_id is required.","required_source_target":"source_id and target_id are required.","same_character":"A character cannot be merged with itself.","character_not_found":"Character not found.","no_face_to_save":"No face detected to save.","character_no_samples":"This character has no face samples.","no_characters":"No characters saved.","empty_query":"empty query","no_confident_shot":"No shot is reliable enough for {who}: the recognized faces are below the confidence threshold. Add more varied samples (Face Hub), then run recognition again.","no_recognized_shot":"No shot recognized for {who} — add face samples (Face Hub), then run “Index faces” and recognition.","no_shared_shot":"No shot contains all the mentioned characters.","partial_character_overlap":"No shot contains all {total} mentioned characters — showing those that contain {found} of them.","cited_character":"a mentioned character","face_engine_missing":"No face engine is available (missing weights/dependencies — run the installation again).","image_unreadable_error":"Could not read image: {error}","no_indexed_face":"No faces have been indexed. Run “Index faces” first.","no_reference_face":"No face detected in the references.","siglip_missing":"SigLIP 2 dependencies are missing: pip install -r requirements.txt ({error})",
        "video_dimensions":"could not determine video dimensions{detail}","gif_dimensions":"could not determine GIF dimensions: {path}","frame_missing":"frame not found at {time:.3f}s","write_source_png":"could not write source PNG","write_upscaled_png":"could not write upscaled PNG","write_depth_png":"could not write depth PNG","write_alpha_png":"could not write alpha PNG","write_preview_png":"could not write preview PNG","write_interpolated_png":"could not write interpolated PNG","unknown_preview_mode":"unknown preview mode: {mode}","depth_unavailable":"depth is unavailable{detail}","removebg_unavailable":"removeBG is unavailable{detail}","interpolation_unavailable":"interpolation is unavailable{detail}","load_depth_failed":"could not load depth model{detail}","load_removebg_failed":"could not load removeBG model{detail}","load_rife_failed":"could not load RIFE{detail}","encoder_stopped":"ffmpeg encoder stopped (codec unavailable?)","empty_output":"output file is empty","empty_gif":"output GIF is empty","empty_alpha":"alpha sequence is empty","empty_depth":"depth sequence is empty","ffmpeg_code":"ffmpeg encode exit code {code}","image_unreadable_path":"could not read image: {path}","write_upscaled_image":"could not write upscaled image","unexpected_rembg":"unexpected removeBG output (shape {shape})","spandrel_not_i2i":"Spandrel model is not image-to-image: {path}","gmfss_missing": "GMFSS is incomplete: {path} — reinstall the model from Settings › Models","drba_arch_missing": "DRBA architecture missing for {model} — install the model from Settings › Models","drba_weights_missing": "DRBA weights missing: {file}","rife_arch_missing": "RIFE architecture missing for {model} — install the model from Settings › Models","rife_weights_missing": "RIFE weights missing: {file}","ntire_code_missing": "NTIRE code missing for {model} — install the model from Settings › Models ({error})","weight_missing":"missing weights: {file}. Download the model from {url}, then place it in {folder}","model_download_failed":"model download failed ({file}): {error}",
        "video_not_found":"video not found: {path}","no_video":"no video is open","point_not_found":"point not found","nothing_to_undo":"no point to undo","no_restore":"no saved state to restore","track_before_dedupe":"run tracking before deduplicating","add_point_first":"add at least one point first","no_matte_scope":"no matte for scope “{scope}”","track_before_export":"run tracking before exporting","no_mask_frame":"no mask on this frame — add points or run tracking","engine_missing":"{engine} is missing — install it in Settings › Models ({error})","engine_failed":"{engine} failed: {error}","fine_matte_unreadable":"fine matte preview is unreadable","track_before_refine":"run tracking before refining the matte","no_propagated_matte":"no propagated matte — run tracking first","segment_before_remove":"segment and propagate the object before removing it","remove_engine_unwired":"removal engine “{engine}” is not connected yet — use {fallback}","engine_weights_missing":"{engine} weights are missing — download them in Settings › Models","engine_unavailable":"{engine} engine is unavailable: {error}","sam_package_missing":"sam2 package is unavailable (pip install sam2): {error}","sam_weights_missing":"SAM weights not found — install SAM 2.1 in Settings › Models","sam3_package_missing":"sam3 package is unavailable (install SAM 3.1 in Settings › Models): {error}","sam3_cuda_required":"SAM 3.1 requires an NVIDIA GPU (CUDA): the upstream model has no CPU path. Use SAM 2.1 on this machine.","sam3_weights_missing":"SAM 3.1 weights not found — install them in Settings › Models","no_frame_to_process":"no frame to process","empty_frame_range":"frame range is empty","preview_out_of_range":"preview frame is outside the selected range","whisper_missing":"faster-whisper is missing: pip install faster-whisper ({error})","parakeet_missing":"Parakeet is missing: pip install onnx-asr[gpu,hub] ({error})","silero_missing":"Silero VAD is missing: pip install silero-vad ({error})","librosa_missing":"librosa is missing: pip install librosa ({error})","ben2_missing":"ben2 package is missing (install BEN2 in Settings › Models): {error}","da3_missing":"depth_anything_3 package is missing (install Depth Anything 3 in Settings › Models): {error}","unknown_seg_model":"unknown cutout model: {model}",
    },
}


# The other languages inherit the same stable keys; only user-facing wording is overridden.
_MESSAGES["es"] = {**_MESSAGES["en"], **{
    "unknown_command":"comando desconocido{detail}","required_name":"El nombre es obligatorio.","required_id":"El id es obligatorio.","required_char_id":"El char_id es obligatorio.","required_source_target":"source_id y target_id son obligatorios.","same_character":"Un personaje no puede fusionarse consigo mismo.","character_not_found":"No se encontró el personaje.","no_face_to_save":"No se detectó ningún rostro para guardar.","character_no_samples":"Este personaje no tiene muestras de rostro.","no_characters":"No hay personajes guardados.","empty_query":"consulta vacía","no_shared_shot":"Ningún plano contiene todos los personajes mencionados.","partial_character_overlap":"Ningún plano contiene los {total} personajes mencionados: se muestran los que contienen {found}.","cited_character":"un personaje mencionado","face_engine_missing":"No hay ningún motor facial disponible (faltan pesos o dependencias; vuelve a ejecutar la instalación).","image_unreadable_error":"No se pudo leer la imagen: {error}","no_indexed_face":"No hay rostros indexados. Ejecuta primero «Indexar rostros».","no_reference_face":"No se detectó ningún rostro en las referencias.","video_dimensions":"no se pudieron determinar las dimensiones del vídeo{detail}","gif_dimensions":"no se pudieron determinar las dimensiones del GIF: {path}","frame_missing":"no se encontró el fotograma en {time:.3f}s","empty_output":"el archivo de salida está vacío","no_video":"no hay ningún vídeo abierto","point_not_found":"no se encontró el punto","nothing_to_undo":"no hay ningún punto que deshacer","track_before_export":"ejecuta el seguimiento antes de exportar","no_propagated_matte":"no hay ningún matte propagado; ejecuta primero el seguimiento","no_frame_to_process":"no hay ningún fotograma que procesar","empty_frame_range":"el intervalo de fotogramas está vacío",
}}
_MESSAGES["de"] = {**_MESSAGES["en"], **{
    "unknown_command":"unbekannter Befehl{detail}","required_name":"Name ist erforderlich.","required_id":"id ist erforderlich.","required_char_id":"char_id ist erforderlich.","required_source_target":"source_id und target_id sind erforderlich.","same_character":"Eine Figur kann nicht mit sich selbst zusammengeführt werden.","character_not_found":"Figur nicht gefunden.","no_face_to_save":"Kein Gesicht zum Speichern erkannt.","character_no_samples":"Diese Figur hat keine Gesichtsbeispiele.","no_characters":"Keine Figuren gespeichert.","empty_query":"leere Suchanfrage","no_shared_shot":"Keine Einstellung enthält alle genannten Figuren.","partial_character_overlap":"Keine Einstellung enthält alle {total} genannten Figuren – gezeigt werden die mit {found}.","cited_character":"eine genannte Figur","face_engine_missing":"Keine Gesichtserkennung verfügbar (Gewichte/Abhängigkeiten fehlen – Installation erneut ausführen).","image_unreadable_error":"Bild konnte nicht gelesen werden: {error}","no_indexed_face":"Keine Gesichter indexiert. Zuerst „Gesichter indexieren“ ausführen.","no_reference_face":"In den Referenzen wurde kein Gesicht erkannt.","video_dimensions":"Videoabmessungen konnten nicht ermittelt werden{detail}","gif_dimensions":"GIF-Abmessungen konnten nicht ermittelt werden: {path}","frame_missing":"Frame bei {time:.3f}s nicht gefunden","empty_output":"Ausgabedatei ist leer","no_video":"kein Video geöffnet","point_not_found":"Punkt nicht gefunden","nothing_to_undo":"kein Punkt zum Rückgängigmachen","track_before_export":"Tracking vor dem Export ausführen","no_propagated_matte":"keine übertragene Matte – zuerst Tracking ausführen","no_frame_to_process":"kein Frame zu verarbeiten","empty_frame_range":"Frame-Bereich ist leer",
}}
_MESSAGES["ja"] = {**_MESSAGES["en"], **{
    "unknown_command":"不明なコマンド{detail}","required_name":"名前を入力してください。","required_id":"id が必要です。","required_char_id":"char_id が必要です。","required_source_target":"source_id と target_id が必要です。","same_character":"同じキャラクター同士を統合することはできません。","character_not_found":"キャラクターが見つかりません。","no_face_to_save":"保存できる顔が検出されませんでした。","character_no_samples":"このキャラクターには顔サンプルがありません。","no_characters":"キャラクターが登録されていません。","empty_query":"検索内容が空です","no_shared_shot":"指定したすべてのキャラクターが映るショットはありません。","partial_character_overlap":"指定した{total}人全員が映るショットはありません。{found}人が映るショットを表示します。","cited_character":"指定したキャラクター","face_engine_missing":"顔認識エンジンを利用できません（重みまたは依存関係がありません。インストールをやり直してください）。","image_unreadable_error":"画像を読み込めませんでした: {error}","no_indexed_face":"顔がインデックス化されていません。先に「顔をインデックス化」を実行してください。","no_reference_face":"参照画像から顔が検出されませんでした。","video_dimensions":"動画のサイズを取得できませんでした{detail}","gif_dimensions":"GIF のサイズを取得できませんでした: {path}","frame_missing":"{time:.3f}秒のフレームが見つかりません","empty_output":"出力ファイルが空です","no_video":"動画が開かれていません","point_not_found":"ポイントが見つかりません","nothing_to_undo":"元に戻すポイントがありません","track_before_export":"書き出す前にトラッキングを実行してください","no_propagated_matte":"伝播済みマットがありません。先にトラッキングを実行してください","no_frame_to_process":"処理するフレームがありません","empty_frame_range":"フレーム範囲が空です",
}}
_MESSAGES["zh"] = {**_MESSAGES["en"], **{
    "unknown_command":"未知命令{detail}","required_name":"名称为必填项。","required_id":"id 为必填项。","required_char_id":"char_id 为必填项。","required_source_target":"source_id 和 target_id 为必填项。","same_character":"角色不能与自身合并。","character_not_found":"找不到角色。","no_face_to_save":"未检测到可保存的人脸。","character_no_samples":"该角色没有人脸样本。","no_characters":"尚未保存任何角色。","empty_query":"搜索内容为空","no_shared_shot":"没有镜头同时包含所有提到的角色。","partial_character_overlap":"没有镜头同时包含提到的 {total} 个角色，显示包含其中 {found} 个的镜头。","cited_character":"提到的角色","face_engine_missing":"没有可用的人脸引擎（缺少权重或依赖项，请重新运行安装）。","image_unreadable_error":"无法读取图像：{error}","no_indexed_face":"尚未索引任何人脸。请先运行“索引人脸”。","no_reference_face":"参考图中未检测到人脸。","video_dimensions":"无法获取视频尺寸{detail}","gif_dimensions":"无法获取 GIF 尺寸：{path}","frame_missing":"找不到 {time:.3f} 秒处的帧","empty_output":"输出文件为空","no_video":"未打开视频","point_not_found":"找不到点","nothing_to_undo":"没有可撤销的点","track_before_export":"请先运行跟踪再导出","no_propagated_matte":"没有已传播的遮罩，请先运行跟踪","no_frame_to_process":"没有可处理的帧","empty_frame_range":"帧范围为空",
}}

# Traductions spécialisées restantes (les noms de moteurs, commandes et paramètres restent tels quels).
_MESSAGES["es"].update({
    "no_confident_shot":"No hay ningún plano lo bastante fiable para {who}: los rostros reconocidos están por debajo del umbral de confianza. Añade muestras más variadas (Hub de rostros) y vuelve a ejecutar el reconocimiento.",
    "no_recognized_shot":"No se reconoció ningún plano para {who}. Añade muestras de rostro (Hub de rostros), ejecuta «Indexar rostros» y vuelve a iniciar el reconocimiento.",
    "siglip_missing":"Faltan las dependencias de SigLIP 2: pip install -r requirements.txt ({error})",
    "write_source_png":"No se pudo escribir el PNG original","write_upscaled_png":"No se pudo escribir el PNG reescalado","write_depth_png":"No se pudo escribir el PNG de profundidad","write_alpha_png":"No se pudo escribir el PNG alfa","write_preview_png":"No se pudo escribir el PNG de vista previa","write_interpolated_png":"No se pudo escribir el PNG interpolado","unknown_preview_mode":"Modo de vista previa desconocido: {mode}",
    "depth_unavailable":"La profundidad no está disponible{detail}","removebg_unavailable":"removeBG no está disponible{detail}","interpolation_unavailable":"La interpolación no está disponible{detail}","load_depth_failed":"No se pudo cargar el modelo de profundidad{detail}","load_removebg_failed":"No se pudo cargar removeBG{detail}","load_rife_failed":"No se pudo cargar RIFE{detail}","encoder_stopped":"El codificador ffmpeg se detuvo (¿códec no disponible?)","empty_gif":"El GIF de salida está vacío","empty_alpha":"La secuencia alfa está vacía","empty_depth":"La secuencia de profundidad está vacía","ffmpeg_code":"ffmpeg terminó con el código {code}","image_unreadable_path":"No se pudo leer la imagen: {path}","write_upscaled_image":"No se pudo escribir la imagen reescalada","unexpected_rembg":"Salida inesperada de removeBG (forma {shape})","spandrel_not_i2i":"El modelo Spandrel no es de imagen a imagen: {path}","gmfss_missing": "GMFSS está incompleto: {path}: reinstala el modelo desde Ajustes › Modelos","drba_arch_missing": "Falta la arquitectura DRBA de {model}: instala el modelo desde Ajustes › Modelos","drba_weights_missing": "Faltan los pesos de DRBA: {file}","rife_arch_missing": "Falta la arquitectura RIFE de {model}: instala el modelo desde Ajustes › Modelos","rife_weights_missing": "Faltan los pesos de RIFE: {file}","ntire_code_missing": "Falta el código NTIRE de {model}: instala el modelo desde Ajustes › Modelos ({error})",
    "weight_missing":"Faltan los pesos: {file}. Descarga el modelo desde {url} y colócalo en {folder}","model_download_failed":"No se pudo descargar el modelo ({file}): {error}","video_not_found":"No se encontró el vídeo: {path}","no_restore":"No hay ninguna copia guardada que restaurar","track_before_dedupe":"Ejecuta el seguimiento antes de eliminar duplicados","add_point_first":"Añade al menos un punto primero","no_matte_scope":"No hay ningún matte para el alcance «{scope}»","no_mask_frame":"No hay máscara en este fotograma: añade puntos o ejecuta el seguimiento",
    "engine_missing":"Falta {engine}; instálalo en Ajustes › Modelos ({error})","engine_failed":"{engine} falló: {error}","fine_matte_unreadable":"No se puede leer la vista previa del matte fino","track_before_refine":"Ejecuta el seguimiento antes de perfeccionar el matte","segment_before_remove":"Segmenta y propaga el objeto antes de eliminarlo","remove_engine_unwired":"El motor de eliminación «{engine}» aún no está conectado; usa {fallback}","engine_weights_missing":"Faltan los pesos de {engine}; descárgalos en Ajustes › Modelos","engine_unavailable":"El motor {engine} no está disponible: {error}","sam_package_missing":"El paquete sam2 no está disponible (pip install sam2): {error}","sam_weights_missing":"No se encontraron los pesos de SAM; instala SAM 2.1 en Ajustes › Modelos","sam3_package_missing":"El paquete sam3 no está disponible (instala SAM 3.1 en Ajustes › Modelos): {error}","sam3_cuda_required":"SAM 3.1 requiere una GPU NVIDIA (CUDA): el modelo original no tiene modo CPU. Usa SAM 2.1 en este equipo.","sam3_weights_missing":"No se encontraron los pesos de SAM 3.1; instálalos en Ajustes › Modelos","preview_out_of_range":"El fotograma de vista previa está fuera del intervalo seleccionado","whisper_missing":"Falta faster-whisper: pip install faster-whisper ({error})","parakeet_missing":"Falta Parakeet: pip install onnx-asr[gpu,hub] ({error})","silero_missing":"Falta Silero VAD: pip install silero-vad ({error})","librosa_missing":"Falta librosa: pip install librosa ({error})","ben2_missing":"Falta el paquete ben2 (instala BEN2 en Ajustes › Modelos): {error}","da3_missing":"Falta el paquete depth_anything_3 (instala Depth Anything 3 en Ajustes › Modelos): {error}","unknown_seg_model":"Modelo de recorte desconocido: {model}",
})
_MESSAGES["de"].update({
    "no_confident_shot":"Keine Einstellung ist für {who} zuverlässig genug: Die erkannten Gesichter liegen unter der Vertrauensschwelle. Füge vielfältigere Beispiele hinzu (Gesichts-Hub) und starte die Erkennung erneut.","no_recognized_shot":"Keine Einstellung für {who} erkannt. Füge Gesichtsbeispiele hinzu (Gesichts-Hub), führe „Gesichter indexieren“ aus und starte die Erkennung.","siglip_missing":"SigLIP-2-Abhängigkeiten fehlen: pip install -r requirements.txt ({error})",
    "write_source_png":"Quell-PNG konnte nicht geschrieben werden","write_upscaled_png":"Hochskaliertes PNG konnte nicht geschrieben werden","write_depth_png":"Tiefen-PNG konnte nicht geschrieben werden","write_alpha_png":"Alpha-PNG konnte nicht geschrieben werden","write_preview_png":"Vorschau-PNG konnte nicht geschrieben werden","write_interpolated_png":"Interpoliertes PNG konnte nicht geschrieben werden","unknown_preview_mode":"Unbekannter Vorschaumodus: {mode}","depth_unavailable":"Tiefenberechnung ist nicht verfügbar{detail}","removebg_unavailable":"removeBG ist nicht verfügbar{detail}","interpolation_unavailable":"Interpolation ist nicht verfügbar{detail}","load_depth_failed":"Tiefenmodell konnte nicht geladen werden{detail}","load_removebg_failed":"removeBG konnte nicht geladen werden{detail}","load_rife_failed":"RIFE konnte nicht geladen werden{detail}","encoder_stopped":"ffmpeg-Encoder wurde beendet (Codec nicht verfügbar?)","empty_gif":"Ausgabe-GIF ist leer","empty_alpha":"Alpha-Sequenz ist leer","empty_depth":"Tiefensequenz ist leer","ffmpeg_code":"ffmpeg wurde mit Code {code} beendet","image_unreadable_path":"Bild konnte nicht gelesen werden: {path}","write_upscaled_image":"Hochskaliertes Bild konnte nicht geschrieben werden","unexpected_rembg":"Unerwartete removeBG-Ausgabe (Form {shape})","spandrel_not_i2i":"Spandrel-Modell ist kein Bild-zu-Bild-Modell: {path}","gmfss_missing": "GMFSS ist unvollständig: {path} – Modell unter Einstellungen › Modelle neu installieren","drba_arch_missing": "DRBA-Architektur für {model} fehlt – Modell unter Einstellungen › Modelle installieren","drba_weights_missing": "DRBA-Gewichte fehlen: {file}","rife_arch_missing": "RIFE-Architektur für {model} fehlt – Modell unter Einstellungen › Modelle installieren","rife_weights_missing": "RIFE-Gewichte fehlen: {file}","ntire_code_missing": "NTIRE-Code für {model} fehlt – Modell unter Einstellungen › Modelle installieren ({error})",
    "weight_missing":"Gewichte fehlen: {file}. Lade das Modell von {url} herunter und lege es in {folder} ab","model_download_failed":"Modelldownload fehlgeschlagen ({file}): {error}","video_not_found":"Video nicht gefunden: {path}","no_restore":"Kein Speicherstand zum Wiederherstellen","track_before_dedupe":"Vor dem Bereinigen Tracking ausführen","add_point_first":"Zuerst mindestens einen Punkt setzen","no_matte_scope":"Keine Matte für den Bereich „{scope}“","no_mask_frame":"Keine Maske auf diesem Frame – Punkte setzen oder Tracking ausführen","engine_missing":"{engine} fehlt – unter Einstellungen › Modelle installieren ({error})","engine_failed":"{engine} ist fehlgeschlagen: {error}","fine_matte_unreadable":"Feine-Matte-Vorschau ist nicht lesbar","track_before_refine":"Vor dem Verfeinern der Matte Tracking ausführen","segment_before_remove":"Objekt vor dem Entfernen segmentieren und übertragen","remove_engine_unwired":"Entfernungs-Engine „{engine}“ ist noch nicht angebunden – verwende {fallback}","engine_weights_missing":"Gewichte für {engine} fehlen – unter Einstellungen › Modelle herunterladen","engine_unavailable":"Engine {engine} ist nicht verfügbar: {error}","sam_package_missing":"sam2-Paket ist nicht verfügbar (pip install sam2): {error}","sam_weights_missing":"SAM-Gewichte nicht gefunden – SAM 2.1 unter Einstellungen › Modelle installieren","sam3_package_missing":"sam3-Paket ist nicht verfügbar (SAM 3.1 unter Einstellungen › Modelle installieren): {error}","sam3_cuda_required":"SAM 3.1 benötigt eine NVIDIA-GPU (CUDA): Das Original-Modell hat keinen CPU-Pfad. Nutze auf diesem Rechner SAM 2.1.","sam3_weights_missing":"SAM-3.1-Gewichte nicht gefunden – unter Einstellungen › Modelle installieren","preview_out_of_range":"Vorschau-Frame liegt außerhalb des ausgewählten Bereichs","whisper_missing":"faster-whisper fehlt: pip install faster-whisper ({error})","parakeet_missing":"Parakeet fehlt: pip install onnx-asr[gpu,hub] ({error})","silero_missing":"Silero VAD fehlt: pip install silero-vad ({error})","librosa_missing":"librosa fehlt: pip install librosa ({error})","ben2_missing":"ben2-Paket fehlt (BEN2 unter Einstellungen › Modelle installieren): {error}","da3_missing":"depth_anything_3-Paket fehlt (Depth Anything 3 unter Einstellungen › Modelle installieren): {error}","unknown_seg_model":"Unbekanntes Freistellungsmodell: {model}",
})
_MESSAGES["ja"].update({
    "no_confident_shot":"{who}について十分に信頼できるショットがありません。認識された顔が信頼度のしきい値を下回っています。より多様なサンプルを顔ハブに追加して、認識を再実行してください。","no_recognized_shot":"{who}のショットを認識できませんでした。顔ハブに顔サンプルを追加し、「顔をインデックス化」と認識を実行してください。","siglip_missing":"SigLIP 2 の依存関係がありません: pip install -r requirements.txt ({error})","write_source_png":"元の PNG を書き込めませんでした","write_upscaled_png":"アップスケール済み PNG を書き込めませんでした","write_depth_png":"深度 PNG を書き込めませんでした","write_alpha_png":"アルファ PNG を書き込めませんでした","write_preview_png":"プレビュー PNG を書き込めませんでした","write_interpolated_png":"補間済み PNG を書き込めませんでした","unknown_preview_mode":"不明なプレビューモード: {mode}","depth_unavailable":"深度処理を利用できません{detail}","removebg_unavailable":"removeBG を利用できません{detail}","interpolation_unavailable":"フレーム補間を利用できません{detail}","load_depth_failed":"深度モデルを読み込めませんでした{detail}","load_removebg_failed":"removeBG を読み込めませんでした{detail}","load_rife_failed":"RIFE を読み込めませんでした{detail}","encoder_stopped":"ffmpeg エンコーダーが停止しました（コーデックを利用できない可能性があります）","empty_gif":"出力 GIF が空です","empty_alpha":"アルファシーケンスが空です","empty_depth":"深度シーケンスが空です","ffmpeg_code":"ffmpeg がコード {code} で終了しました","image_unreadable_path":"画像を読み込めませんでした: {path}","write_upscaled_image":"アップスケール済み画像を書き込めませんでした","unexpected_rembg":"removeBG の出力形式が不正です（形状 {shape}）","spandrel_not_i2i":"Spandrel モデルは画像変換モデルではありません: {path}","gmfss_missing": "GMFSS が不完全です: {path} — 設定 › モデルから再インストールしてください","drba_arch_missing": "{model} の DRBA アーキテクチャがありません。設定 › モデルからインストールしてください","drba_weights_missing": "DRBA の重みがありません: {file}","rife_arch_missing": "{model} の RIFE アーキテクチャがありません。設定 › モデルからインストールしてください","rife_weights_missing": "RIFE の重みがありません: {file}","ntire_code_missing": "{model} の NTIRE コードがありません。設定 › モデルからインストールしてください（{error}）",
    "weight_missing":"重みがありません: {file}。{url} からモデルをダウンロードし、{folder} に配置してください","model_download_failed":"モデルのダウンロードに失敗しました（{file}）: {error}","video_not_found":"動画が見つかりません: {path}","no_restore":"復元できる保存データがありません","track_before_dedupe":"重複を整理する前にトラッキングを実行してください","add_point_first":"先にポイントを1つ以上追加してください","no_matte_scope":"範囲「{scope}」のマットがありません","no_mask_frame":"このフレームにはマスクがありません。ポイントを追加するかトラッキングを実行してください","engine_missing":"{engine} がありません。設定 › モデルからインストールしてください（{error}）","engine_failed":"{engine} が失敗しました: {error}","fine_matte_unreadable":"高精細マットのプレビューを読み込めません","track_before_refine":"マットを調整する前にトラッキングを実行してください","segment_before_remove":"オブジェクトを削除する前に、セグメント化して伝播してください","remove_engine_unwired":"削除エンジン「{engine}」はまだ接続されていません。{fallback} を使用してください","engine_weights_missing":"{engine} の重みがありません。設定 › モデルからダウンロードしてください","engine_unavailable":"{engine} エンジンを利用できません: {error}","sam_package_missing":"sam2 パッケージを利用できません（pip install sam2）: {error}","sam_weights_missing":"SAM の重みが見つかりません。設定 › モデルから SAM 2.1 をインストールしてください","sam3_package_missing":"sam3 パッケージを利用できません（設定 › モデルから SAM 3.1 をインストールしてください）: {error}","sam3_cuda_required":"SAM 3.1 には NVIDIA GPU（CUDA）が必要です。上流モデルに CPU 実行の経路はありません。この環境では SAM 2.1 を使ってください。","sam3_weights_missing":"SAM 3.1 の重みが見つかりません。設定 › モデルからインストールしてください","preview_out_of_range":"プレビューフレームが選択範囲外です","whisper_missing":"faster-whisper がありません: pip install faster-whisper ({error})","parakeet_missing":"Parakeet がありません: pip install onnx-asr[gpu,hub] ({error})","silero_missing":"Silero VAD がありません: pip install silero-vad ({error})","librosa_missing":"librosa がありません: pip install librosa ({error})","ben2_missing":"ben2 パッケージがありません（設定 › モデルから BEN2 をインストールしてください）: {error}","da3_missing":"depth_anything_3 パッケージがありません（設定 › モデルから Depth Anything 3 をインストールしてください）: {error}","unknown_seg_model":"不明な切り抜きモデル: {model}",
})
_MESSAGES["zh"].update({
    "no_confident_shot":"没有足够可靠的镜头可匹配{who}：识别出的人脸低于置信度阈值。请在人脸中心添加更多不同的样本，然后重新运行识别。","no_recognized_shot":"没有识别出{who}的镜头。请在人脸中心添加人脸样本，然后运行“索引人脸”和识别。","siglip_missing":"缺少 SigLIP 2 依赖项：pip install -r requirements.txt ({error})","write_source_png":"无法写入原始 PNG","write_upscaled_png":"无法写入放大后的 PNG","write_depth_png":"无法写入深度 PNG","write_alpha_png":"无法写入 Alpha PNG","write_preview_png":"无法写入预览 PNG","write_interpolated_png":"无法写入补帧 PNG","unknown_preview_mode":"未知预览模式：{mode}","depth_unavailable":"深度处理不可用{detail}","removebg_unavailable":"removeBG 不可用{detail}","interpolation_unavailable":"补帧不可用{detail}","load_depth_failed":"无法加载深度模型{detail}","load_removebg_failed":"无法加载 removeBG{detail}","load_rife_failed":"无法加载 RIFE{detail}","encoder_stopped":"ffmpeg 编码器已停止（编码器可能不可用）","empty_gif":"输出 GIF 为空","empty_alpha":"Alpha 序列为空","empty_depth":"深度序列为空","ffmpeg_code":"ffmpeg 以代码 {code} 退出","image_unreadable_path":"无法读取图像：{path}","write_upscaled_image":"无法写入放大后的图像","unexpected_rembg":"removeBG 输出异常（形状 {shape}）","spandrel_not_i2i":"Spandrel 模型不是图像到图像模型：{path}","gmfss_missing": "GMFSS 不完整：{path} — 请在设置 › 模型中重新安装","drba_arch_missing": "缺少 {model} 的 DRBA 架构 — 请在设置 › 模型中安装","drba_weights_missing": "缺少 DRBA 权重：{file}","rife_arch_missing": "缺少 {model} 的 RIFE 架构 — 请在设置 › 模型中安装","rife_weights_missing": "缺少 RIFE 权重：{file}","ntire_code_missing": "缺少 {model} 的 NTIRE 代码 — 请在设置 › 模型中安装（{error}）",
    "weight_missing":"缺少权重：{file}。请从 {url} 下载模型并放入 {folder}","model_download_failed":"模型下载失败（{file}）：{error}","video_not_found":"找不到视频：{path}","no_restore":"没有可恢复的保存内容","track_before_dedupe":"请先运行跟踪再清理重复项","add_point_first":"请先添加至少一个点","no_matte_scope":"范围“{scope}”没有遮罩","no_mask_frame":"当前帧没有遮罩，请添加点或运行跟踪","engine_missing":"缺少 {engine}，请在设置 › 模型中安装（{error}）","engine_failed":"{engine} 失败：{error}","fine_matte_unreadable":"无法读取精细遮罩预览","track_before_refine":"请先运行跟踪再细化遮罩","segment_before_remove":"请先分割并传播对象再将其移除","remove_engine_unwired":"移除引擎“{engine}”尚未接入，请使用 {fallback}","engine_weights_missing":"缺少 {engine} 权重，请在设置 › 模型中下载","engine_unavailable":"{engine} 引擎不可用：{error}","sam_package_missing":"sam2 包不可用（pip install sam2）：{error}","sam_weights_missing":"找不到 SAM 权重，请在设置 › 模型中安装 SAM 2.1","sam3_package_missing":"sam3 包不可用（请在设置 › 模型中安装 SAM 3.1）：{error}","sam3_cuda_required":"SAM 3.1 需要 NVIDIA GPU（CUDA）：上游模型没有 CPU 路径。请在本机改用 SAM 2.1。","sam3_weights_missing":"找不到 SAM 3.1 权重 — 请在设置 › 模型中安装","preview_out_of_range":"预览帧超出所选范围","whisper_missing":"缺少 faster-whisper：pip install faster-whisper ({error})","parakeet_missing":"缺少 Parakeet：pip install onnx-asr[gpu,hub] ({error})","silero_missing":"缺少 Silero VAD：pip install silero-vad ({error})","librosa_missing":"缺少 librosa：pip install librosa ({error})","ben2_missing":"缺少 ben2 包（请在设置 › 模型中安装 BEN2）：{error}","da3_missing":"缺少 depth_anything_3 包（请在设置 › 模型中安装 Depth Anything 3）：{error}","unknown_seg_model":"未知的抠图模型：{model}",
})

_MESSAGES["fr"].update({"ffmpeg_missing":"ffmpeg introuvable : {error}","frame_extraction_failed":"extraction des frames échouée","no_extracted_frame":"aucune frame extraite","ffmpeg_failed":"ffmpeg a échoué"})
_MESSAGES["en"].update({"ffmpeg_missing":"ffmpeg was not found: {error}","frame_extraction_failed":"frame extraction failed","no_extracted_frame":"no frame was extracted","ffmpeg_failed":"ffmpeg failed"})
_MESSAGES["es"].update({"ffmpeg_missing":"No se encontró ffmpeg: {error}","frame_extraction_failed":"Falló la extracción de fotogramas","no_extracted_frame":"No se extrajo ningún fotograma","ffmpeg_failed":"ffmpeg falló"})
_MESSAGES["de"].update({"ffmpeg_missing":"ffmpeg wurde nicht gefunden: {error}","frame_extraction_failed":"Frame-Extraktion fehlgeschlagen","no_extracted_frame":"Kein Frame wurde extrahiert","ffmpeg_failed":"ffmpeg ist fehlgeschlagen"})
_MESSAGES["ja"].update({"ffmpeg_missing":"ffmpeg が見つかりません: {error}","frame_extraction_failed":"フレームの抽出に失敗しました","no_extracted_frame":"フレームを抽出できませんでした","ffmpeg_failed":"ffmpeg が失敗しました"})
_MESSAGES["zh"].update({"ffmpeg_missing":"找不到 ffmpeg：{error}","frame_extraction_failed":"帧提取失败","no_extracted_frame":"未提取到任何帧","ffmpeg_failed":"ffmpeg 失败"})


def language():
    code = os.environ.get("NR_LANG", "fr").lower().replace("_", "-").split("-", 1)[0]
    return code if code in _MESSAGES else "fr"


def t(key, **values):
    """Renvoie la traduction, avec repli français et paramètres techniques conservés."""
    text = _MESSAGES[language()].get(key) or _MESSAGES["fr"].get(key) or key
    return text.format(**values)
